channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=23.1.2
- pip:
  - mlflow==2.12.2
  - pandas==2.0.3
  - pathlib==1.0.1
  - psutil==5.9.5
  - scikit-learn==1.2.2
  - xgboost==2.0.3
name: mlflow-env
